// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kznvbcmyfdmvmbprartq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt6bnZiY215ZmRtdm1icHJhcnRxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY4MTQ3NzAsImV4cCI6MjA3MjM5MDc3MH0.P7RxILKwSJXMZp4wfy7GBh3zRMIxQK2HSNyvgbaIctM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});